version: "3"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapy
    depends_on:
      - privoxy
    tty: true
    volumes:
      - .:/crawler
    env_file:
      - .env
  tor:
    image: osminogin/tor-simple
  privoxy:
    image: splazit/privoxy-alpine
    volumes:
      - ./privoxy-config:/etc/privoxy/config
    depends_on:
      - tor
